### ISSUE TITLE
Combine pre-processor with calibration GUI

### ISSUE THREAD

**Issue by walgren** [maestrolab/SMAREACTcleaned#7]
Add a table to the calibration GUI and add the relevant pre-processor so everything is in one place. This will involve changing the file organization, function references, and formatting. When this is done, see if we can add an option to skip the ASMADA file reading.

**Comment by walgren** [comment]
I'm skeptical that I have the time to do this... The pre-processor GUI is not in a format that would be easy to translate to a "tab" of the existing calibration GUI (i.e., there are 100+ references to "mainWindow," which changes context when it's a tab). This task may take 50+ hours of code refactoring...

Additionally, philosophically, the two GUIs (pre-processing and calibration) do fundamentally different things. I am not sure it makes sense to combine them. The required work to integrate them (i.e., create export functions and data objects to go from pre-processing to calibration) might not be worthwhile.

**Comment by mingear** [comment]
this is fine.
